config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :mentions, only: :index
  resources :tweets do
    resource :like
    resources :comments do
      resource :like
    end
  end
  resources :users, except: %i[new create index] do
    resource :subscription
  end
  resources :notifications, only: %i[index] do
    collection do
      post :mark_as_read
    end
  end
  root 'tweets#index'
end

app/models/comment.rb
# frozen_string_literal: true

# comment model
class Comment < ApplicationRecord
  after_create_commit { broadcast_prepend_to 'comments' }
  after_update_commit { broadcast_replace_to 'comments' }
  after_destroy_commit { broadcast_remove_to 'comments' }

  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_rich_text :body
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :notifications, as: :notifiable
  validates :body, presence: true, if: -> { rich_text_body.body.attachments.none? }
  after_create :notify_mentioned_users

  def mentions
    regex = /@(\w+)/

    body.to_s.scan(regex).flatten
  end

  def mentioned_users
    User.where(username: mentions)
  end

  def notify_mentioned_users
    mentioned_users.each do |mentioned_user|
      notifications.create(recipient: mentioned_user,
                           user: user,
                           action: 'mentioned')
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# comments controller
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet
  before_action :set_comment, only: %i[update destroy]
  after_action :create_notification, only: :create

  def create
    @comment = @tweet.comments.new(comment_params)

    if @comment.save
      # trigger turbo stream
      @tweet.update(updated_at: Time.now)
      respond_to do |format|
        format.json { render json: {}, status: :ok }
        format.html { redirect_to @tweet }
      end
    else
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(@tweet, partial: 'comments/form', locals: { tweet: @tweet })
      end
      format.html { render :new }
      format.json { render json: @comment.errors, status: :unprocessable_entity }
    end
  end

  def update
    if @comment.update(comment_params)
      format.html { redirect_to @tweet, notice: 'Comment updated.' }
      format.json { render :index, status: :created }
    else
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(@tweet, partial: 'comments/form', locals: { tweet: @tweet })
      end
      format.html { render :new }
      format.json { render json: @comment.errors, status: :unprocessable_entity }
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @tweet, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end

  def set_comment
    @comment = @tweet.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment)
          .permit(%i[id body tweet_id])
          .merge(user_id: current_user.id)
  end

  def create_notification
    return if @tweet.user == current_user

    @tweet.notifications.create(recipient: @tweet.user,
                                user: current_user,
                                action: 'commented')
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

# comments helper
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag dom_id(comment) do %>
  <% return unless comment.persisted? %>
  <div class="px-5 py-4 bg-white dark:bg-gray-800 shadow rounded-lg w-screen max-w-xl" style="margin-bottom: 30px;">
    <div class="flex mb-4">
      <img class="w-12 h-12 rounded-full" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"/>
      <div class="ml-2 mt-0.5">
        <span class="block font-medium text-base leading-snug text-black dark:text-gray-100"><%= comment.user.name %></span>
        <span class="block text-sm text-gray-500 dark:text-gray-400 font-light leading-snug"><%= comment.created_at.strftime('%-d %B at %H:%M') %></span>
      </div>
    </div>
    <p class="text-gray-800 dark:text-gray-100 leading-snug md:leading-normal"><%= comment.body %></p>
    <div class="flex justify-between items-center mt-5" data-tweet-target="ignore">
      <div class="flex ">
        <%= button_to tweet_comment_like_path(comment.commentable, comment), data: { controller: 'likes', likes_user_ids_value: comment.likes.pluck(:user_id) } do %>
          <div data-likes-target="unliked" class="hidden">
            <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
            </svg>
          </div>
          <div data-likes-target="liked" class="hidden">
            <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clip-rule="evenodd" />
            </svg>
          </div>
        <% end %>
        <span class="ml-1 text-gray-500 dark:text-gray-400 font-light"><%= comment.likes.count %></span>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [tweet, comment], id: dom_id(comment)) do |form|%>
  <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
    <div class="sm:flex sm:items-start">
      <div class="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
        <!-- Heroicon name: exclamation -->
        <svg class="h-6 w-6 text-red-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>
      </div>
      <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
        <h3 class="text-lg leading-6 text-gray-900" id="modal-headline">
          <%= tweet.body %>
        </h3>
        <div class="mt-2">
          <!-- <p class="text-sm text-gray-500"> -->
            <%#= form.rich_text_area :body, class: 'p-4 rounded-xl resize-none w-96', placeholder: 'Tweet your reply', data: { controller: 'mentions', mentions_target: 'field' } %>
            <%#= form.rich_text_area :body, placeholder: 'Tweet your reply', data: { controller: 'mentions', mentions_target: 'field' } %>
          <%= form.rich_text_area :body, placeholder: 'What do you want to say?', data: { controller: 'mentions', mentions_target: 'field' }, id: "comment_body_tweet_#{tweet.id}" %>
          <!-- </p> -->
        </div>
      </div>
    </div>
  </div>
  <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
    <%= form.submit 'Reply', class: 'w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-red-600 text-base font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:ml-3 sm:w-auto sm:text-sm' %>
    <button type="button"
            class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"
            data-action="click->modal#handleModal">
      Cancel
    </button>
  </div>
<% end %>

app/views/comments/_modal.html.erb
<div class="fixed z-10 inset-0 overflow-y-auto">
  <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
    <!--
      Background overlay, show/hide based on modal state.

      Entering: "ease-out duration-300"
        From: "opacity-0"
        To: "opacity-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100"
        To: "opacity-0"
    -->
    <div class="fixed inset-0 transition-opacity" aria-hidden="true">
      <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
    </div>

    <!-- This element is to trick the browser into centering the modal contents. -->
    <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
    <!--
      Modal panel, show/hide based on modal state.

      Entering: "ease-out duration-300"
        From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        To: "opacity-100 translate-y-0 sm:scale-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100 translate-y-0 sm:scale-100"
        To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
    -->
    <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full" role="dialog" aria-modal="true" aria-labelledby="modal-headline">
      <%= turbo_frame_tag dom_id(comment) do %>
        <%= render 'comments/form', tweet: tweet, comment: comment %>
      <% end %>
    </div>
  </div>
</div>