config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :mentions, only: :index
  resources :tweets do
    resource :like
    resources :comments do
      resource :like
    end
  end
  resources :users, except: %i[new create index] do
    resource :subscription
  end
  resources :notifications, only: %i[index] do
    collection do
      post :mark_as_read
    end
  end
  root 'tweets#index'
end

app/models/tweet.rb
# frozen_string_literal: true

# tweet model
class Tweet < ApplicationRecord
  after_create_commit { broadcast_prepend_to 'tweets' }
  after_update_commit { broadcast_replace_to 'tweets' }
  after_destroy_commit { broadcast_remove_to 'tweets' }

  belongs_to :user
  belongs_to :original_tweet, class_name: 'Tweet', optional: true
  has_rich_text :body
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  validates :body, presence: true, if: -> { rich_text_body.body.attachments.none? }
  has_many :notifications, as: :notifiable
  after_create :notify_mentioned_users

  def mentions
    regex = /@(\w+)/

    body.to_s.scan(regex).flatten
  end

  def mentioned_users
    User.where(username: mentions)
  end

  def notify_mentioned_users
    mentioned_users.each do |mentioned_user|
      notifications.create(recipient: mentioned_user,
                           user: user,
                           action: 'mentioned')
    end
  end
end

app/controllers/tweets_controller.rb
# frozen_string_literal: true

# tweets controller
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: %i[show edit update destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweet = Tweet.new
    ids = [current_user.id, *subscriptions]
    @tweets = Tweet.where('user_id IN (?) OR id IN (?)', ids, mentions)
                   .order(created_at: :desc)
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @comment = @tweet.comments.build
    @comments = @tweet.comments.order(created_at: :desc)
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit; end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_path, notice: 'Tweet was successfully created.' }
        format.json { render :index, status: :created }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(@tweet, partial: 'tweets/form', locals: { tweet: @tweet })
        end
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(@tweet, partial: 'tweets/form', locals: { tweet: @tweet })
        end
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])

    authorize! @tweet
  end

  # Only allow a list of trusted parameters through.
  def tweet_params
    params.require(:tweet)
          .permit(:body, :likes_count, :retweets_count)
          .merge(user: current_user)
  end

  def subscriptions
    current_user.subscriptions.pluck(:followee_id)
  end

  def mentions
    Tweet.select { |tweet| current_user.id.in?(tweet.mentioned_users.ids) }.pluck(:id)
  end
end

app/helpers/tweets_helper.rb
# frozen_string_literal: true

# tweets helper
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, id: dom_id(tweet)) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-8 w-screen max-w-xl flex flex-col">
    <% if tweet.persisted? %>
      <%= form.rich_text_area :body, placeholder: 'What do you want to say?', data: { controller: 'mentions', mentions_target: 'field' } %>
      <%= button_to 'Cancel', @tweet, class: 'py-3 my-8 text-lg bg-gradient-to-r from-purple-500 to-indigo-600 rounded-xl text-white max-w-lg' %>
      <%= form.submit 'Tweet', class: 'py-3 my-8 text-lg bg-gradient-to-r from-purple-500 to-indigo-600 rounded-xl text-white max-w-lg' %>
    <% else %>
      <%#= form.rich_text_area :body, class: 'p-4 rounded-xl max-w-xl resize-none', placeholder: 'What do you want to say?', data: { controller: 'mentions', mentions_target: 'field' } %>
      <%= form.rich_text_area :body, placeholder: 'What do you want to say?', data: { controller: 'mentions', mentions_target: 'field' } %>
      <%= form.submit 'Tweet', class: 'py-3 my-8 text-lg bg-gradient-to-r from-purple-500 to-indigo-600 rounded-xl text-white' %>
    <% end %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<%= turbo_frame_tag dom_id(tweet) do %>
  <div data-controller="tweet" data-action="click->tweet#goTo", data-tweet-url-value="<%= tweet_path(tweet) %>">
    <div class="px-5 py-4 bg-white dark:bg-gray-800 shadow rounded-lg w-screen max-w-xl" style="margin-bottom: 30px;">
      <div class="flex mb-4">
        <div data-tweet-target="avatar">
          <%= link_to tweet.user, data: { turbo_frame: '_top' } do %>
            <img class="w-12 h-12 rounded-full" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"/>
          <% end %>
        </div>
        <div class="ml-2 mt-0.5">
          <span class="block font-medium text-base leading-snug text-black dark:text-gray-100" data-tweet-target="username"><%= link_to tweet.user.name, tweet.user, data: { turbo_frame: '_top' } %></span>
          <span class="block text-sm text-gray-500 dark:text-gray-400 font-light leading-snug"><%= tweet.created_at.strftime('%-d %B at %H:%M') %></span>
        </div>
      </div>
      <p class="text-gray-800 dark:text-gray-100 leading-snug md:leading-normal"><%= tweet.body %></p>
      <div class="flex justify-between items-center mt-5" data-tweet-target="ignore">
        <div class="flex ">
          <%= button_to tweet_like_path(tweet), data: { controller: 'likes', likes_user_ids_value: tweet.likes.pluck(:user_id) } do %>
            <div data-likes-target="unliked" class="hidden">
              <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
              </svg>
            </div>
            <div data-likes-target="liked" class="hidden">
              <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clip-rule="evenodd" />
              </svg>
            </div>
          <% end %>
          <span class="ml-1 text-gray-500 dark:text-gray-400 font-light"><%= tweet.likes.count %></span>
          &nbsp;
          <div data-controller="modal" class="flex">
            <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" data-action="click->modal#handleModal">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
            </svg>
            <span class="ml-1 text-gray-500 dark:text-gray-400 font-light"><%= tweet.comments.count %></span>
            <div class="hidden" data-modal-target="window">
              <%= render 'comments/modal', tweet: tweet, comment: tweet.comments.build %>
            </div>
          </div>
        </div>
        <div class="ml-1 text-gray-500 dark:text-gray-400 font-light">
          <div class="hidden" data-controller="visibility" data-visibility-user-id-value="<%= tweet.user_id %>">
            <%= link_to 'Edit', edit_tweet_path(tweet) %>
            <%= link_to 'Delete', tweet_path(tweet), method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<%= turbo_frame_tag dom_id(@tweet) do %>
  <div class="px-5 py-4 bg-white dark:bg-gray-800 shadow rounded-lg w-screen max-w-xl" style="margin-bottom: 30px;">
    <div class="flex mb-4">
      <img class="w-12 h-12 rounded-full" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"/>
      <div class="ml-2 mt-0.5">
        <span class="block font-medium text-base leading-snug text-black dark:text-gray-100"><%= @tweet.user.name %></span>
        <span class="block text-sm text-gray-500 dark:text-gray-400 font-light leading-snug"><%= @tweet.created_at.strftime('%-d %B at %H:%M') %></span>
      </div>
    </div>
    <p class="text-gray-800 dark:text-gray-100 leading-snug md:leading-normal"><%= render 'form', tweet: @tweet %></p>
  </div>
<% end %>

app/views/tweets/index.html.erb
<% if current_user.present? %>
  <div class="bg-gray-200 w-full flex flex-col items-center">
    <%= turbo_frame_tag 'tweet_form' do %>
      <%= render 'tweets/form', tweet: @tweet %>
    <% end %>
  </div>
<% end %>
<div class="p-8 bg-gray-50 dark:bg-gray-900 flex justify-center w-screen h-screen">
  <div>
    <p id="notice"><%= notice %></p>
    <%= turbo_stream_from 'tweets' %>
    <%= turbo_frame_tag 'tweets' do %>
      <%= render @tweets %>
    <% end %>
  </div>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-3xl">
  <%= link_to '&larr;'.html_safe, tweets_path %>
  Tweet
</h1>
<%= turbo_stream_from 'tweets' %>
<%= turbo_frame_tag dom_id(@tweet) do %>
  <%= render @tweet %>
<% end %>
<%= turbo_stream_from 'comments' %>
<%= turbo_frame_tag 'comments' do %>
  <%= render @comments %>
<% end %>