config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :mentions, only: :index
  resources :tweets do
    resource :like
    resources :comments do
      resource :like
    end
  end
  resources :users, except: %i[new create index] do
    resource :subscription
  end
  resources :notifications, only: %i[index] do
    collection do
      post :mark_as_read
    end
  end
  root 'tweets#index'
end

app/models/user.rb
# frozen_string_literal: true

# user model
class User < ApplicationRecord
  include ActionText::Attachable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :notifications, as: :notifiable
  has_many :subscriptions, dependent: :destroy
  validates :name, presence: true
  validates :username, presence: true, uniqueness: true

  def to_trix_content_attachment_partial_path
    to_partial_path
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

# devise registrations controller
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: %i[create]
  # before_action :configure_account_update_params, only: [:update]
  # before_action :configure_permitted_parameters, if: :devise_controller?

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email password password_confirmation name username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: %i[create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[email password password_confirmation])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# users controller
class UsersController < ApplicationController
  include OnboardingsConcern
  before_action :user
  before_action :onboarding_completion, only: :show

  def show
    @tweets = @user.tweets
                   .where
                   .not(id: nil)
                   .order(created_at: :desc)
    @tweet = @user.tweets.new
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :username)
  end

  def onboarding_completion
    steps = OnboardingsConcern.instance_methods
    complete = steps.select { |step| send(step) }
    @onboarding_completion = complete.length / steps.length.to_f * 100
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# users helper
module UsersHelper
  def unsubscribed?
    current_user.subscriptions
                .where(followee_id: @user.id)
                .none?
  end

  def following(user)
    user.subscriptions
  end

  def followers(user)
    Subscription.where(followee_id: user.id)
  end
end

app/views/users/_user.html.erb
<span class="mention">
  <a href="<%= user_path(user.id) %>" data-turbo-frame="_top"><%= "@#{user.username}" %></a>
</span>

app/views/users/edit.html.erb
<!-- <div class="bg-gray-200 w-full flex flex-col">
  <div class="flex mb-4 mt-4 ml-4">
    <img class="w-20 h-20 rounded-full" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"/>
    <div class="ml-2 mt-0.5">
      <span class="block font-medium text-base leading-snug text-black dark:text-gray-100"><%= @user.name %></span>
      <span class="block text-sm text-gray-500 dark:text-gray-400 font-light leading-snug"><%= "@#{@user.username}" %></span>
      <span class="block text-sm text-gray-500 dark:text-gray-400 font-light leading-snug"><%= "Following: #{following(@user).count}" %></span>
      <span class="block text-sm text-gray-500 dark:text-gray-400 font-light leading-snug"><%= "Followers: #{followers(@user).count}" %></span>
    </div>
  </div>
</div> -->
<div class="min-w-screen min-h-screen bg-gray-200 flex items-center justify-center px-5 pb-10 pt-16">
  <div class="w-full mx-auto rounded-lg bg-white shadow-lg p-5 text-gray-700" style="max-width: 600px">
    <div class="mb-10">
      <h1 class="text-center font-bold text-xl uppercase">Edit profile</h1>
    </div>
    <%= form_with(model: @user, local: true) do |form| %>
      <div class="mb-3">
        <%= form.label :name, class: 'font-bold text-sm mb-2 ml-1' %>
        <div>
          <%= form.text_field :name, class: 'w-full px-3 py-2 mb-1 border-2 border-gray-200 rounded-md focus:outline-none focus:border-indigo-500 transition-colors', placeholder: 'Name' %>
        </div>
      </div>
      <div class="mb-3">
        <%= form.label :username, class: 'font-bold text-sm mb-2 ml-1' %>
        <div>
          <%= form.text_field :username, class: 'w-full px-3 py-2 mb-1 border-2 border-gray-200 rounded-md focus:outline-none focus:border-indigo-500 transition-colors', placeholder: 'Name' %>
        </div>
      </div>
      <div>
        <%= form.submit 'Save', class: 'block w-full max-w-xs mx-auto bg-indigo-500 hover:bg-indigo-700 focus:bg-indigo-700 text-white rounded-lg px-3 py-3 font-semibold' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="bg-gray-200 w-full flex flex-col">
  <div class="flex mb-4 mt-4 ml-4">
    <img class="w-20 h-20 rounded-full" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"/>
    <div class="ml-2 mt-0.5">
      <span class="block font-medium text-base leading-snug text-black dark:text-gray-100"><%= @user.name %></span>
      <span class="block text-sm text-gray-500 dark:text-gray-400 font-light leading-snug"><%= "@#{@user.username}" %></span>
      <span class="block text-sm text-gray-500 dark:text-gray-400 font-light leading-snug"><%= "Following: #{following(@user).count}" %></span>
      <span class="block text-sm text-gray-500 dark:text-gray-400 font-light leading-snug"><%= "Followers: #{followers(@user).count}" %></span>
      <span class="block text-sm text-gray-500 dark:text-gray-400 font-light leading-snug">Profile completion: <%= @onboarding_completion.round %>%</span>
    </div>
  </div>
  <div class="absolute top-15 right-10">
    <% if current_user == @user %>
      <%= button_to 'Edit Profile', edit_user_path(@user), class: 'py-3 my-8 text-lg bg-gradient-to-r from-purple-500 to-indigo-600 pl-4 pr-4 rounded-xl text-white max-w-lg', method: :get %>
    <% else %>
      <%= button_to unsubscribed? ? 'Follow' : 'Unfollow', user_subscription_path(@user), class: 'py-3 my-8 text-lg bg-gradient-to-r from-purple-500 to-indigo-600 pl-4 pr-4 rounded-xl text-white max-w-lg' %>
    <% end %>
</div>
</div>
<div class="p-8 bg-gray-50 dark:bg-gray-900 flex justify-center w-screen h-screen">
  <div>
    <p id="notice"><%= notice %></p>
    <%= turbo_stream_from 'tweets' %>
    <%= turbo_frame_tag 'tweets' do %>
      <%= render @tweets %>
    <% end %>
  </div>
</div>